blank_issues_enabled: false
contact_links:
  - name: "Ask general usage question on mumax³ mailing list"
    url: https://groups.google.com/g/mumax2
    about: Please ask general usage questions on the mumax³ mailing list, where the whole mumax³ community can help you by answering your questions and/or learn from the given answers.
