package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"github.com/mumax/3/cuda/cu"
	"github.com/mumax/3/timer"
	"sync"
	"unsafe"
)

// CUDA handle for shifty kernel
var shifty_code cu.Function

// Stores the arguments for shifty kernel invocation
type shifty_args_t struct {
	arg_dst    unsafe.Pointer
	arg_src    unsafe.Pointer
	arg_Nx     int
	arg_Ny     int
	arg_Nz     int
	arg_shy    int
	arg_clampD float32
	arg_clampU float32
	argptr     [8]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for shifty kernel invocation
var shifty_args shifty_args_t

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	shifty_args.argptr[0] = unsafe.Pointer(&shifty_args.arg_dst)
	shifty_args.argptr[1] = unsafe.Pointer(&shifty_args.arg_src)
	shifty_args.argptr[2] = unsafe.Pointer(&shifty_args.arg_Nx)
	shifty_args.argptr[3] = unsafe.Pointer(&shifty_args.arg_Ny)
	shifty_args.argptr[4] = unsafe.Pointer(&shifty_args.arg_Nz)
	shifty_args.argptr[5] = unsafe.Pointer(&shifty_args.arg_shy)
	shifty_args.argptr[6] = unsafe.Pointer(&shifty_args.arg_clampD)
	shifty_args.argptr[7] = unsafe.Pointer(&shifty_args.arg_clampU)
}

// Wrapper for shifty CUDA kernel, asynchronous.
func k_shifty_async(dst unsafe.Pointer, src unsafe.Pointer, Nx int, Ny int, Nz int, shy int, clampD float32, clampU float32, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("shifty")
	}

	shifty_args.Lock()
	defer shifty_args.Unlock()

	if shifty_code == 0 {
		shifty_code = fatbinLoad(shifty_map, "shifty")
	}

	shifty_args.arg_dst = dst
	shifty_args.arg_src = src
	shifty_args.arg_Nx = Nx
	shifty_args.arg_Ny = Ny
	shifty_args.arg_Nz = Nz
	shifty_args.arg_shy = shy
	shifty_args.arg_clampD = clampD
	shifty_args.arg_clampU = clampU

	args := shifty_args.argptr[:]
	cu.LaunchKernel(shifty_code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("shifty")
	}
}

// maps compute capability on PTX code for shifty kernel.
var shifty_map = map[int]string{0: "",
	75:  shifty_ptx_75,
	80:  shifty_ptx_80,
	86:  shifty_ptx_86,
	87:  shifty_ptx_87,
	89:  shifty_ptx_89,
	90:  shifty_ptx_90,
	100: shifty_ptx_100,
	120: shifty_ptx_120}

// shifty PTX code for various compute capabilities.
const (
	shifty_ptx_75 = `
.version 8.8
.target sm_75
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_80 = `
.version 8.8
.target sm_80
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_86 = `
.version 8.8
.target sm_86
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_87 = `
.version 8.8
.target sm_87
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_89 = `
.version 8.8
.target sm_89
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_90 = `
.version 8.8
.target sm_90
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 shifty_param_0,
	.param .u64 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<22>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r6, [shifty_param_3];
	ld.param.u32 	%r8, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r9, %ntid.x;
	mov.u32 	%r10, %ctaid.x;
	mov.u32 	%r11, %tid.x;
	mad.lo.s32 	%r1, %r10, %r9, %r11;
	mov.u32 	%r12, %ntid.y;
	mov.u32 	%r13, %ctaid.y;
	mov.u32 	%r14, %tid.y;
	mad.lo.s32 	%r2, %r13, %r12, %r14;
	mov.u32 	%r15, %ntid.z;
	mov.u32 	%r16, %ctaid.z;
	mov.u32 	%r17, %tid.z;
	mad.lo.s32 	%r3, %r16, %r15, %r17;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r2, %r6;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r8;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r4, %r2, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;

	setp.ge.s32 	%p7, %r4, %r6;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;

	mad.lo.s32 	%r18, %r3, %r6, %r4;
	mad.lo.s32 	%r19, %r18, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r19, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];

$L__BB0_4:
	mad.lo.s32 	%r20, %r3, %r6, %r2;
	mad.lo.s32 	%r21, %r20, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r21, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;

$L__BB0_5:
	ret;

}

`
	shifty_ptx_100 = `
.version 8.8
.target sm_100
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 .ptr .align 1 shifty_param_0,
	.param .u64 .ptr .align 1 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .b32 	%r<26>;
	.reg .f32 	%f<6>;
	.reg .b64 	%rd<9>;

	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r8, [shifty_param_3];
	ld.param.u32 	%r9, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %ntid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %ntid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r17, %r14, %r15, %r16;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %tid.z;
	mad.lo.s32 	%r21, %r18, %r19, %r20;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r17, %r8;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r21, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;
	sub.s32 	%r4, %r17, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;
	setp.ge.u32 	%p7, %r4, %r8;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;
	mad.lo.s32 	%r22, %r8, %r21, %r4;
	mad.lo.s32 	%r23, %r22, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r23, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];
$L__BB0_4:
	mad.lo.s32 	%r24, %r8, %r21, %r17;
	mad.lo.s32 	%r25, %r24, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r25, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;
$L__BB0_5:
	ret;

}
`
	shifty_ptx_120 = `
.version 8.8
.target sm_120
.address_size 64

	// .globl	shifty

.visible .entry shifty(
	.param .u64 .ptr .align 1 shifty_param_0,
	.param .u64 .ptr .align 1 shifty_param_1,
	.param .u32 shifty_param_2,
	.param .u32 shifty_param_3,
	.param .u32 shifty_param_4,
	.param .u32 shifty_param_5,
	.param .f32 shifty_param_6,
	.param .f32 shifty_param_7
)
{
	.reg .pred 	%p<8>;
	.reg .b32 	%r<26>;
	.reg .f32 	%f<6>;
	.reg .b64 	%rd<9>;

	ld.param.u64 	%rd1, [shifty_param_0];
	ld.param.u64 	%rd2, [shifty_param_1];
	ld.param.u32 	%r5, [shifty_param_2];
	ld.param.u32 	%r8, [shifty_param_3];
	ld.param.u32 	%r9, [shifty_param_4];
	ld.param.u32 	%r7, [shifty_param_5];
	ld.param.f32 	%f5, [shifty_param_6];
	ld.param.f32 	%f4, [shifty_param_7];
	mov.u32 	%r11, %ctaid.x;
	mov.u32 	%r12, %ntid.x;
	mov.u32 	%r13, %tid.x;
	mad.lo.s32 	%r1, %r11, %r12, %r13;
	mov.u32 	%r14, %ctaid.y;
	mov.u32 	%r15, %ntid.y;
	mov.u32 	%r16, %tid.y;
	mad.lo.s32 	%r17, %r14, %r15, %r16;
	mov.u32 	%r18, %ctaid.z;
	mov.u32 	%r19, %ntid.z;
	mov.u32 	%r20, %tid.z;
	mad.lo.s32 	%r21, %r18, %r19, %r20;
	setp.ge.s32 	%p1, %r1, %r5;
	setp.ge.s32 	%p2, %r17, %r8;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r21, %r9;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_5;
	sub.s32 	%r4, %r17, %r7;
	setp.lt.s32 	%p6, %r4, 0;
	@%p6 bra 	$L__BB0_4;
	setp.ge.u32 	%p7, %r4, %r8;
	mov.f32 	%f5, %f4;
	@%p7 bra 	$L__BB0_4;
	mad.lo.s32 	%r22, %r8, %r21, %r4;
	mad.lo.s32 	%r23, %r22, %r5, %r1;
	cvta.to.global.u64 	%rd3, %rd2;
	mul.wide.s32 	%rd4, %r23, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f5, [%rd5];
$L__BB0_4:
	mad.lo.s32 	%r24, %r8, %r21, %r17;
	mad.lo.s32 	%r25, %r24, %r5, %r1;
	cvta.to.global.u64 	%rd6, %rd1;
	mul.wide.s32 	%rd7, %r25, 4;
	add.s64 	%rd8, %rd6, %rd7;
	st.global.f32 	[%rd8], %f5;
$L__BB0_5:
	ret;

}
`
)
